export const schools = [
  {census_id: '00001', school_name: "DE LA SALLE COLLEGE", school_address: "COLOMBO 15."},
  {census_id: '00002', school_name: "MODARA ANANDA M.M.V", school_address: "COLOMBO 15."},
  {census_id: '00003', school_name: "ST.ANTHONY'S B.M.V.", school_address: "MUTWAL,COLOMBO 15."},
  {census_id: '00004', school_name: "KUMARA V.", school_address: "KOTAHENA,COLOMBO 13."},
  {census_id: '00005', school_name: "MATT.ST.JOHN'S M.V.", school_address: "CENTER ROAD,COLOMBO 15."},
  {census_id: '00006', school_name: "ST.LUCIA'S COLLEGE", school_address: "COLOMBO 13."},
  {census_id: '00007', school_name: "CATHEDRAL BOYS COLLEGE", school_address: "KOTAHENA STREET,COLOMBO 13."},
  {census_id: '00008', school_name: "KOTAHENA PRESIDENT COLLEGE", school_address: "ALWIS ROAD,COLOMBO 13."},
  {census_id: '00009', school_name: "ST.ANDREW'S V.", school_address: "LUNUPOKUNA,COLOMBO 15."},
  {census_id: '00010', school_name: "SRI MEDHANANDA V.", school_address: "ST.JAME'S STREET,COLOMBO 15."},
  {census_id: '00011', school_name: "MODARA ST.JOHN'S V", school_address: "MODARA STREET,COLOMBO 15."},
  {census_id: '00012', school_name: "AVE MARIA V.", school_address: "COLOMBO 15."},
  {census_id: '00013', school_name: "SRI SANGHABODHI V.", school_address: "GRANDPASS,COLOMBO 14."},
  {census_id: '00014', school_name: "BLOEMENDHAL SIN.V", school_address: "SIRIMAVO BANDARANAYAKA MAWATHA,COLOMBO 14."},
  {census_id: '00015', school_name: "SRI GUNANANDA V.", school_address: "JINANANDA MAWATHA,COLOMBO 13."},
  {census_id: '00011', school_name: "THOTAWATTA METHODIST V.", school_address: "CHURCH ROAD,COLOMBO 15."},
  {census_id: '00012', school_name: "ROMAN CATHOLIC B.V. ", school_address: "WASALA ROAD,COLOMBO 13."},
  {census_id: '00013', school_name: "ST.JAME'S P.V", school_address: "MUTWAL MAWATHA,COLOMBO 15."},
  {census_id: '00014', school_name: "MAHAWATTA ST.ANTHONY'S SIN.V", school_address: "JAYANTHA MALLAMARACHCHI MAWATHA,COLOMBO 14."},
  {census_id: '00015', school_name: "ST.ANTHONY'S B.P.V. ", school_address: "MADAMPITIYA ROAD,COLOMBO 15."},
  {census_id: '00016', school_name: "AGAMETHI V.", school_address: "BLOEMENDHAL ROAD,COLOMBO 15."},
  {census_id: '00017', school_name: "KOTAHENA M.M.V.", school_address: "MAHA VIDYALA MAWATHA,COLOMBO 13."},
  {census_id: '00018', school_name: "SRI SANGARAJA M.M.V.", school_address: "SRI SANGARAJA MAWATHA,COLOMBO 10."},
  {census_id: '00019', school_name: "MAHABODHI V.", school_address: "FOSTER LANE,COLOMBO 10."},
  {census_id: '00020', school_name: "RAJASINGHE M.V", school_address: "BASELINE ROAD,COLOMBO 09."},
]