name: Platformer Generated uat-web-workflow Build
'on':
  push:
    branches:
      - UAT
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: docker.pkg.github.com/smoerlk/portal-web/portal-web
      CONTAINER_REGISTRY: docker.pkg.github.com
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/heads/}-${{github.sha}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD_B994E954_3B70_4C2B_A5E9_0296CF49AF5A }}
      - name: Build the Docker image
        run: docker build --tag ${SERVICE_NAME}:${{steps.event-version.outputs.SOURCE_TAG }} --file Dockerfile .
      - name: GitHub Image Push
        run: docker push $SERVICE_NAME:${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_9C3024FE_1021_46C1_AD53_159DD68065F3}}
          project-id: ${{secrets.PROJECT_ID_9C3024FE_1021_46C1_AD53_159DD68065F3}}
          token: ${{secrets.AUTOGENERATED_CICD_9C3024FE_1021_46C1_AD53_159DD68065F3}}
          image-name: ${{env.SERVICE_NAME}}
          tag: ${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: f77e5566-9167-44d1-b4f1-354fce240fab
